#!/bin/bash

# Autobuild the Image on Docker Hub with advanced options and buildx for multiarch images
# read more: https://github.com/Tob1asDocker/dockerhubhooksexample

set -ex

echo "### RUN pre_build START: QEMU and buildx ###"

docker run --rm --privileged tonistiigi/binfmt --install all
docker buildx create --use --name multiarchbuilder
docker buildx ls

echo "### RUN pre_build END ###"