name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    strategy:
        matrix:
          version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/.
          platforms: ${{ vars.DOCKER_PLATFORM }}
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}:${{ matrix.version }}-latest
          build-args: PYTHON_VERSION=${{ matrix.version }}